language: python
python:
    - "3.5"
    - "3.6"
install: 
    - pip install -r requirements.txt
    - pip install -U git+https://github.com/quantopian/qgrid --no-deps
    - pip install -U git+https://github.com/ozgur/python-linkedin --no-deps
script:
    - python setup.py unittests
