dist: focal
sudo: true
language: python
python:
    - "3.9"
addons:
-  apt:
-    packages:
    - ffmpeg
    - build-dep
    - graphviz
    - libgfortran3
    - libblas-dev
    - liblapack-dev
    - gfortran      
    - libgeos-dev
install: 
    - pip install -r requirements.txt
    - pip install mplfinance
    - export PYTHONPATH=src
script:
    - python setup.py unittests
